### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [wiseaidev/duckduckgo#5]
- [x] add all fields to [`Response`](https://github.com/wiseaidev/duckduckgo/blob/main/src/response.rs):

```sh
{
  "Abstract": "",
  "AbstractSource": "Wikipedia",
  "AbstractText": "",
  "AbstractURL": "https://en.wikipedia.org/wiki/Rust_(disambiguation)",
  "Answer": "",
  "AnswerType": "",
  "Definition": "",
  "DefinitionSource": "",
  "DefinitionURL": "",
  "Entity": "",
  "Heading": "Rust",
  "Image": "",
  "ImageHeight": 0,
  "ImageIsLogo": 0,
  "ImageWidth": 0,
  "Infobox": "",
  "Redirect": "",
  "RelatedTopics": [
    {
      "FirstURL": "https://duckduckgo.com/Rust?kp=1",
      "Icon": {
        "Height": "",
        "URL": "/i/2f16ac81.jpg",
        "Width": ""
      },
      "Result": "<a href=\"https://duckduckgo.com/Rust?kp=1\">Rust</a> An iron oxide, a usually reddish-brown oxide formed by the reaction of iron and oxygen in the...",
      "Text": "Rust An iron oxide, a usually reddish-brown oxide formed by the reaction of iron and oxygen in the..."
    },
    {
      "FirstURL": "https://duckduckgo.com/Rust_(programming_language)?kp=1",
      "Icon": {
        "Height": "",
        "URL": "/i/832f249b.png",
        "Width": ""
      },
      "Result": "<a href=\"https://duckduckgo.com/Rust_(programming_language)?kp=1\">Rust (programming language)</a>A multi-paradigm, general-purpose programming language.",
      "Text": "Rust (programming language) A multi-paradigm, general-purpose programming language."
    },
    {
      "FirstURL": "https://duckduckgo.com/Rust_(video_game)?kp=1",
      "Icon": {
        "Height": 16,
        "URL": "/i/playrust.com.ico",
        "Width": 16
      },
      "Result": "<a href=\"https://duckduckgo.com/Rust_(video_game)?kp=1\">Rust (video game)</a>A multiplayer-only survival video game developed by Facepunch Studios.",
      "Text": "Rust (video game) A multiplayer-only survival video game developed by Facepunch Studios."
    },
  ],
  "Results": [],
  "Type": "D",
  "meta": {
    "attribution": null,
    "blockgroup": null,
    "created_date": null,
    "description": "Wikipedia",
    "designer": null,
    "dev_date": null,
    "dev_milestone": "live",
    "developer": [
      {
        "name": "DDG Team",
        "type": "ddg",
        "url": "http://www.duckduckhack.com"
      }
    ],
    "example_query": "nikola tesla",
    "id": "wikipedia_fathead",
    "is_stackexchange": null,
    "js_callback_name": "wikipedia",
    "live_date": null,
    "maintainer": {
      "github": "duckduckgo"
    },
    "name": "Wikipedia",
    "perl_module": "DDG::Fathead::Wikipedia",
    "producer": null,
    "production_state": "online",
    "repo": "fathead",
    "signal_from": "wikipedia_fathead",
    "src_domain": "en.wikipedia.org",
    "src_id": 1,
    "src_name": "Wikipedia",
    "src_options": {
      "directory": "",
      "is_fanon": 0,
      "is_mediawiki": 1,
      "is_wikipedia": 1,
      "language": "en",
      "min_abstract_length": "20",
      "skip_abstract": 0,
      "skip_abstract_paren": 0,
      "skip_end": "0",
      "skip_icon": 0,
      "skip_image_name": 0,
      "skip_qr": "",
      "source_skip": "",
      "src_info": ""
    },
    "src_url": null,
    "status": "live",
    "tab": "About",
    "topic": [
      "productivity"
    ],
    "unsafe": 0
  }
}

```

- [x] add [all params](https://duckduckgo.com/duckduckgo-help-pages/settings/params/).
- [x] add all backends: "api", "html" ?
